[package]
name = "gale-hw-asus-ec"
version.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later"

[dependencies]
gale-hw = { path = "../gale-hw" }
gale-pawnio = { path = "../gale-pawnio" }
tracing = "0.1"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_System_Registry"] }
