[package]
name = "gale-pawnio"
version.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later"

[dependencies]
tracing = "0.1"

[target.'cfg(windows)'.dependencies]
libloading = "0.9"
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_Security", "Win32_System_Threading", "Win32_System_Registry"] }

[dev-dependencies]
sha2 = "0.11"
